baseurl = "/mongo-java-driver/3.0"
languageCode = "en-us"
title = "MongoDB Java Driver"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true

[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 90
    identifier = "apiDocs"
    url = "http://api.mongodb.org/java/3.0"
